WITH  CTE1 AS(
SELECT EMP_NAME, DEPT_NAME, SALARY,
DENSE_RANK () OVER (PARTITION BY DEPT_NAME ORDER BY SALARY DESC) AS RANKED_SALARY
FROM EMPLOYEE)
SELECT EMP_NAME, DEPT_NAME, SALARY
FROM CTE1
WHERE RANKED_SALARY = 1
ORDER BY SALARY DESC
;
